### ISSUE TITLE
Audio doesn't play on question feedback in Authoring Tool

### ISSUE THREAD

**Issue by RobertPeek** [deltanet/adapt-audio#91]

**Comment by dancgray** [comment]
This line is returning false in audio question built in authoring tool:
https://github.com/deltanet/adapt-audio/blob/master/js/audio-controls-view.js#L108

Because properties schema does not have the correct structure/elements
https://github.com/deltanet/adapt-audio/blob/master/properties.schema#L915

https://github.com/deltanet/adapt-audio/blob/master/example.json#L86
